config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :consulting_rooms
  resources :patients
  resources :medics
  root "appointments#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/medic.rb
class Medic < ApplicationRecord
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController
  before_action :set_medic, only: [:show, :edit, :update, :destroy]

  # GET /medics
  # GET /medics.json
  def index
    @medics = Medic.all
  end

  # GET /medics/1
  # GET /medics/1.json
  def show
  end

  # GET /medics/new
  def new
    @medic = Medic.new
  end

  # GET /medics/1/edit
  def edit
  end

  # POST /medics
  # POST /medics.json
  def create
    @medic = Medic.new(medic_params)

    respond_to do |format|
      if @medic.save
        format.html { redirect_to @medic, notice: 'Medic was successfully created.' }
        format.json { render :show, status: :created, location: @medic }
      else
        format.html { render :new }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medics/1
  # PATCH/PUT /medics/1.json
  def update
    respond_to do |format|
      if @medic.update(medic_params)
        format.html { redirect_to @medic, notice: 'Medic was successfully updated.' }
        format.json { render :show, status: :ok, location: @medic }
      else
        format.html { render :edit }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medics/1
  # DELETE /medics/1.json
  def destroy
    @medic.destroy
    respond_to do |format|
      format.html { redirect_to medics_url, notice: 'Medic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medic
      @medic = Medic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medic_params
      params.require(:medic).permit(:nombre, :apellido, :identificacion, :celular, :tipo)
    end
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/views/medics/_form.html.erb
<%= form_with(model: medic, local: true) do |form| %>
  <% if medic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medic.errors.count, "error") %> prohibited this medic from being saved:</h2>

      <ul>
        <% medic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :identificacion %>
    <%= form.text_field :identificacion %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medics/edit.html.erb
<h1>Editing Medic</h1>

<%= render 'form', medic: @medic %>

<%= link_to 'Show', @medic %> |
<%= link_to 'Back', medics_path %>

app/views/medics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medics</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Identificacion</th>
      <th>Celular</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medics.each do |medic| %>
      <tr>
        <td><%= medic.nombre %></td>
        <td><%= medic.apellido %></td>
        <td><%= medic.identificacion %></td>
        <td><%= medic.celular %></td>
        <td><%= medic.tipo %></td>
        <td><%= link_to 'Show', medic %></td>
        <td><%= link_to 'Edit', edit_medic_path(medic) %></td>
        <!--<td><%= link_to 'Destroy', medic, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medic', new_medic_path %>
<%= link_to 'Back', appointments_path %>

app/views/medics/new.html.erb
<h1>New Medic</h1>

<%= render 'form', medic: @medic %>

<%= link_to 'Back', medics_path %>

app/views/medics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @medic.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @medic.apellido %>
</p>

<p>
  <strong>Identificacion:</strong>
  <%= @medic.identificacion %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @medic.celular %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @medic.tipo %>
</p>

<%= link_to 'Edit', edit_medic_path(@medic) %> |
<%= link_to 'Back', medics_path %>