config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :consulting_rooms
  resources :patients
  resources :medics
  root "appointments#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/consulting_room.rb
class ConsultingRoom < ApplicationRecord
end

app/controllers/consulting_rooms_controller.rb
class ConsultingRoomsController < ApplicationController
  before_action :set_consulting_room, only: [:show, :edit, :update, :destroy]

  # GET /consulting_rooms
  # GET /consulting_rooms.json
  def index
    @consulting_rooms = ConsultingRoom.all
  end

  # GET /consulting_rooms/1
  # GET /consulting_rooms/1.json
  def show
  end

  # GET /consulting_rooms/new
  def new
    @consulting_room = ConsultingRoom.new
  end

  # GET /consulting_rooms/1/edit
  def edit
  end

  # POST /consulting_rooms
  # POST /consulting_rooms.json
  def create
    @consulting_room = ConsultingRoom.new(consulting_room_params)

    respond_to do |format|
      if @consulting_room.save
        format.html { redirect_to @consulting_room, notice: 'Consulting room was successfully created.' }
        format.json { render :show, status: :created, location: @consulting_room }
      else
        format.html { render :new }
        format.json { render json: @consulting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consulting_rooms/1
  # PATCH/PUT /consulting_rooms/1.json
  def update
    respond_to do |format|
      if @consulting_room.update(consulting_room_params)
        format.html { redirect_to @consulting_room, notice: 'Consulting room was successfully updated.' }
        format.json { render :show, status: :ok, location: @consulting_room }
      else
        format.html { render :edit }
        format.json { render json: @consulting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consulting_rooms/1
  # DELETE /consulting_rooms/1.json
  def destroy
    @consulting_room.destroy
    respond_to do |format|
      format.html { redirect_to consulting_rooms_url, notice: 'Consulting room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consulting_room
      @consulting_room = ConsultingRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consulting_room_params
      params.require(:consulting_room).permit(:nombre, :codigo, :ubicacion, :tipo)
    end
end

app/helpers/consulting_rooms_helper.rb
module ConsultingRoomsHelper
end

app/views/consulting_rooms/_form.html.erb
<%= form_with(model: consulting_room, local: true) do |form| %>
  <% if consulting_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consulting_room.errors.count, "error") %> prohibited this consulting_room from being saved:</h2>

      <ul>
        <% consulting_room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consulting_rooms/edit.html.erb
<h1>Editing Consulting Room</h1>

<%= render 'form', consulting_room: @consulting_room %>

<%= link_to 'Show', @consulting_room %> |
<%= link_to 'Back', consulting_rooms_path %>

app/views/consulting_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consulting Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Ubicacion</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consulting_rooms.each do |consulting_room| %>
      <tr>
        <td><%= consulting_room.nombre %></td>
        <td><%= consulting_room.codigo %></td>
        <td><%= consulting_room.ubicacion %></td>
        <td><%= consulting_room.tipo %></td>
        <td><%= link_to 'Show', consulting_room %></td>
        <td><%= link_to 'Edit', edit_consulting_room_path(consulting_room) %></td>
        <!--<td><%= link_to 'Destroy', consulting_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consulting Room', new_consulting_room_path %>
<%= link_to 'Back', appointments_path %>

app/views/consulting_rooms/new.html.erb
<h1>New Consulting Room</h1>

<%= render 'form', consulting_room: @consulting_room %>

<%= link_to 'Back', consulting_rooms_path %>

app/views/consulting_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @consulting_room.nombre %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @consulting_room.codigo %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @consulting_room.ubicacion %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @consulting_room.tipo %>
</p>

<%= link_to 'Edit', edit_consulting_room_path(@consulting_room) %> |
<%= link_to 'Back', consulting_rooms_path %>