config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :consulting_rooms
  resources :patients
  resources :medics
  root "appointments#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :consulting_room
  belongs_to :medic
  belongs_to :patient
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:consulting_room_id, :patient_id, :medic_id, :fecha_cita, :hora_inicio, :hora_fin, :motivo)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :consulting_room_id %>
    <%= form.text_field :consulting_room_id %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.text_field :patient_id %>
  </div>

  <div class="field">
    <%= form.label :medic_id %>
    <%= form.text_field :medic_id %>
  </div>

  <div class="field">
    <%= form.label :fecha_cita %>
    <%= form.date_select :fecha_cita %>
  </div>

  <div class="field">
    <%= form.label :hora_inicio %>
    <%= form.time_select :hora_inicio %>
  </div>

  <div class="field">
    <%= form.label :hora_fin %>
    <%= form.time_select :hora_fin %>
  </div>

  <div class="field">
    <%= form.label :motivo %>
    <%= form.text_field :motivo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>
<table>
  <thead>
    <tr>
      <th>Nombre medico</th>
      <th>Apellido medico</th>
      <th>Nombre paciente</th>
      <th>Apellido paciente</th>
      <th>Nombre del consiltorio</th>
      <th>Codigo del consultorio</th>
      <th>Ubicacion del consultorio</th>
      <th>Fecha cita</th>
      <th>Hora inicio</th>
      <th>Hora fin</th>
      <th>Motivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <!--<td><%= appointment.consulting_room_id %></td>
        <td><%= appointment.patient_id %></td>
        <td><%= appointment.medic_id %></td>-->
        <td><%= Medic.find_by(id: appointment.medic_id).nombre %></td>
        <td><%= Medic.find_by(id: appointment.medic_id).apellido %></td>
        <td><%= Patient.find_by(id: appointment.patient_id).nombre %></td>
        <td><%= Patient.find_by(id: appointment.patient_id).apellido %></td>
        <td><%= ConsultingRoom.find_by(id: appointment.consulting_room_id).nombre %></td>
        <td><%= ConsultingRoom.find_by(id: appointment.consulting_room_id).codigo %></td>
        <td><%= ConsultingRoom.find_by(id: appointment.consulting_room_id).ubicacion %></td>
        <td><%= appointment.fecha_cita %></td>
        <td><%= appointment.hora_inicio %></td>
        <td><%= appointment.hora_fin %></td>
        <td><%= appointment.motivo %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <!--<td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>
<%= link_to 'Patients', patients_path %>
<%= link_to 'Medics', medics_path %>
<%= link_to 'Consulting rooms', consulting_rooms_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre medico</strong>
  <%= Medic.find_by(id: @appointment.medic_id).nombre %>
</p>

<p>
  <strong>Apellido medico</strong>
  <%= Medic.find_by(id: @appointment.medic_id).apellido %>
</p>

<p>
  <strong>Nombre paciente</strong>
  <%= Patient.find_by(id: @appointment.patient_id).nombre %>
</p>

<p>
  <strong>Apellido paciente</strong>
  <%= Patient.find_by(id: @appointment.patient_id).apellido %>
</p>

<p>
  <strong>Nombre del consiltorio</strong>
  <%= ConsultingRoom.find_by(id: @appointment.consulting_room_id).nombre %>
</p>

<p>
  <strong>Codigo del consultorio</strong>
  <%= ConsultingRoom.find_by(id: @appointment.consulting_room_id).codigo %>
</p>

<p>
  <strong>Ubicacion del consultorio</strong>
  <%= ConsultingRoom.find_by(id: @appointment.consulting_room_id).ubicacion %>
</p>

<p>
  <strong>Fecha cita:</strong>
  <%= @appointment.fecha_cita %>
</p>

<p>
  <strong>Hora inicio:</strong>
  <%= @appointment.hora_inicio %>
</p>

<p>
  <strong>Hora fin:</strong>
  <%= @appointment.hora_fin %>
</p>

<p>
  <strong>Motivo:</strong>
  <%= @appointment.motivo %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>